# Generated by Django 5.0.4 on 2024-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupform',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
